### ISSUE TITLE
New PR should have automatically assigned `Ynteam active` project

### ISSUE THREAD

**Issue by jakubjezek001** [ynput/ops-repo-automation#22]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Please describe the feature you have in mind and explain what the current shortcomings are?

Currrently every new PR has to have manually assigned `Ynteam active` project

### How would you imagine the implementation of the feature?

It would be awesome if avery new PR would be automatically have assigned Ynteam Planning project.

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the feature request.

**Comment by philnewm** [comment]
Thats good stuff :+1: 
The idea itself is pretty easy to implement since github provides a bunch of built in event triggers like one for pull requests
```yaml
on:
  pull_request:
    types:
      - opened
    paths:
      - '.github/workflows/**'
      - '.github/CODEOWNERS'
      - 'package*.json'
```

The bigger challenge here is to implement a standardized approach for all intended repositories.
Cause mainting such globally wnated workflows on a per repo basis is simply pointless.

So I see too options here
* Implement a workflow which can create PRs for multiple repos at once to suggest workflow updates
* Implement [workflows on organization](https://docs.github.com/en/actions/sharing-automations/creating-workflow-templates-for-your-organization) level so hopefully all repos can just inherit them

**Comment by jakubjezek001** [comment]
Good questions. Let's first assume that it is something we want to be automated - and I am assuming there is no reason we do not, right @dee-ynput ?

I believe this should be organization wide workflow and only purpose is to simply attach `Ynput Active` project to a PR, in case a PR is assigned to anyone (trigger).

**Comment by mkolar** [comment]
Definitelly and org wide workflow

**Comment by philnewm** [comment]
I tested this now with [ayon-maya](https://github.com/ynput/ayon-maya/pull/183) and it does already work for all newly created prs

@jakubjezek001 should the status be set to anything or is "No status" fine as long as the PR is assigned to the project?

**Comment by philnewm** [comment]
This is now implemented and pushed to all addon repos [bb9327](https://github.com/ynput/ops-repo-automation/commit/bb9327215fd0cefa2110ed677235bd2aec9638d4)
