### ISSUE TITLE
Every new issue with auto assigned project `AYON backlog`

### ISSUE THREAD

**Issue by jakubjezek001** [ynput/ops-repo-automation#23]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Please describe the feature you have in mind and explain what the current shortcomings are?

Currently every new issue needs to have manually assigned `AYON backlog`.

### How would you imagine the implementation of the feature?

It would be great if this had been done automatically. Status could be set to New.

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the feature request.

**Comment by philnewm** [comment]
Thats good stuff :+1: 
The idea itself is pretty easy to implement since github provides a bunch of built in event triggers like one for issues
```yaml
on:
  issues:
    types:
      - opened
```

The bigger challenge here is to implement a standardized approach for all intended repositories.
Cause mainting such globally wnated workflows on a per repo basis is simply pointless.

So I see too options here
* Implement a workflow which can create PRs for multiple repos at once to suggest workflow updates
* Implement [workflows on organization](https://docs.github.com/en/actions/sharing-automations/creating-workflow-templates-for-your-organization) level so hopefully all repos can just inherit them

**Comment by mkolar** [comment]
You might be missunderstanding backlog. 

Each issue that is worth considering to be worked on goes on the backlog. But Code owners of repos are responsible for doing the first issue triage and getting them in there. This would pollute the backlog with all random publicly created issues as well, which is really not desired. 

If you create an issue on your own managed repo, put it in the backlog too (assumption is that as code owner you have a good reason) if someone else creates an issue on a repo they don't manage, the code owner should triage it first
